package io.kubefinops.gitops;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

@Slf4j
@Service
public class ManifestService {

    @org.springframework.beans.factory.annotation.Value("${gitops.simulated-repo-path:deploy/gitops-repo-sim}")
    private String simulatedRepoPath;

    public void updateManifest(String workloadRef, String namespace, Map<String, String> resources) {
        try {
            Path baseRepoPath = Path.of(simulatedRepoPath);
            if (!baseRepoPath.isAbsolute()) {
                baseRepoPath = Path.of(System.getProperty("user.dir")).resolve(simulatedRepoPath);
            }
            
            // Fix for running from sub-module directory
            if (baseRepoPath.toString().contains("services/gitops-bot") && !simulatedRepoPath.startsWith("/")) {
                 // If we are in submodule, we need to go up to project root
                 baseRepoPath = Path.of(System.getProperty("user.dir")).getParent().getParent().resolve(simulatedRepoPath);
            }

            Path repoPath = baseRepoPath.resolve(namespace);
            Files.createDirectories(repoPath);
            
            String fileName = workloadRef.replace("/", "-") + ".yaml";
            File manifestFile = repoPath.resolve(fileName).toFile();
            
            String content = generateManifestContent(workloadRef, namespace, resources);
            
            try (FileWriter writer = new FileWriter(manifestFile)) {
                writer.write(content);
            }
            
            log.info("MANIFEST UPDATED: {}", manifestFile.getAbsolutePath());
        } catch (IOException e) {
            log.error("Failed to update manifest for {}", workloadRef, e);
        }
    }

    private String generateManifestContent(String workloadRef, String namespace, Map<String, String> resources) {
        return String.format("""
                # Autogenerated by KubeFinOps Autopilot
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: %s
                  namespace: %s
                spec:
                  template:
                    spec:
                      containers:
                      - name: app
                        resources:
                          requests:
                            cpu: %s
                            memory: %s
                          limits:
                            cpu: %s
                            memory: %s
                """, 
                workloadRef.split("/")[1], 
                namespace,
                resources.getOrDefault("cpu", "100m"),
                resources.getOrDefault("memory", "128Mi"),
                resources.getOrDefault("cpu", "100m"),
                resources.getOrDefault("memory", "128Mi")
        );
    }
}
