package io.kubefinops.gitops;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

@Slf4j
@Service
public class ManifestService {

    public void updateManifest(String basePath, String workloadRef, String namespace, Map<String, String> resources, Double savings, String currency) {
        try {
            Path baseRepoPath = Path.of(basePath);
            Path repoPath = baseRepoPath.resolve(namespace);
            Files.createDirectories(repoPath);
            
            String fileName = workloadRef.replace("/", "-") + ".yaml";
            File manifestFile = repoPath.resolve(fileName).toFile();
            
            String content = generateManifestContent(workloadRef, namespace, resources, savings, currency);
            
            try (FileWriter writer = new FileWriter(manifestFile)) {
                writer.write(content);
            }
            
            log.info("MANIFEST UPDATED: {} (Estimated savings: {} {})", manifestFile.getAbsolutePath(), savings, currency);
        } catch (IOException e) {
            log.error("Failed to update manifest for {}", workloadRef, e);
        }
    }

    private String generateManifestContent(String workloadRef, String namespace, Map<String, String> resources, Double savings, String currency) {
        return String.format("""
                # Autogenerated by KubeFinOps Autopilot
                # Estimated Monthly Savings: %.2f %s
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: %s
                  namespace: %s
                spec:
                  template:
                    spec:
                      containers:
                      - name: app
                        resources:
                          requests:
                            cpu: %s
                            memory: %s
                          limits:
                            cpu: %s
                            memory: %s
                """, 
                savings != null ? savings : 0.0,
                currency != null ? currency : "USD",
                workloadRef.split("/")[1], 
                namespace,
                resources.getOrDefault("cpu", "100m"),
                resources.getOrDefault("memory", "128Mi"),
                resources.getOrDefault("cpu", "100m"),
                resources.getOrDefault("memory", "128Mi")
        );
    }
}
